### PR TITLE
add background and adjust backdrop

### PR DESCRIPTION
**Pull request by voidzone**
Makes it so that the right text isn't floating in space and hard to read when the bar's not full.

https://i.imgur.com/vf8fJcI.png

### CODE REVIEW

**Comment by voidzone** [comment]
The screenshot it also using the following bar texture:

`"Interface\\RaidFrame\\Raid-Bar-Hp-Fill"`

**Comment by Twintop** [comment]
I'm going to sit on this one for a little bit until I have an option added to options to disable the background as well (won't take long, in fairness). Having this if you don't have a border set at all (NYI) could make it really look like right text is floating in space. I can see wanting a background but some might not (myself included).

**Comment by Twintop** [comment]
This also furthers the need for Lib-SharedMedia in the (at least) BfA version!

**Comment by voidzone** [comment]
Ya, I'm running a pretty small bar with border=1

**Pull request merged**
